export const countries = [
  { code: 'AFG', name: 'AFGHANISTAN (AFG)', prefix: '+93' },
  { code: 'ALA', name: 'ALAND ISLANDS (ALA)', prefix: '+358' },
  { code: 'ALB', name: 'ALBANIA (ALB)', prefix: '+355' },
  { code: 'DZA', name: 'ALGERIA (DZA)', prefix: '+213' },
  { code: 'ASM', name: 'AMERICAN SAMOA (ASM)', prefix: '+1-684' },
  { code: 'AND', name: 'ANDORRA (AND)', prefix: '+376' },
  { code: 'AGO', name: 'ANGOLA (AGO)', prefix: '+244' },
  { code: 'AIA', name: 'ANGUILLA (AIA)', prefix: '+1-264' },
  { code: 'ATA', name: 'ANTARCTICA (ATA)', prefix: '+672' },
  { code: 'ATG', name: 'ANTIGUA AND BARBUDA (ATG)', prefix: '+1-268' },
  { code: 'ARG', name: 'ARGENTINA (ARG)', prefix: '+54' },
  { code: 'ARM', name: 'ARMENIA (ARM)', prefix: '+374' },
  { code: 'ABW', name: 'ARUBA (ABW)', prefix: '+297' },
  { code: 'AUS', name: 'AUSTRALIA (AUS)', prefix: '+61' },
  { code: 'AUT', name: 'AUSTRIA (AUT)', prefix: '+43' },
  { code: 'AZE', name: 'AZERBAIJAN (AZE)', prefix: '+994' },
  { code: 'BHS', name: 'BAHAMAS (BHS)', prefix: '+1-242' },
  { code: 'BHR', name: 'BAHRAIN (BHR)', prefix: '+973' },
  { code: 'BGD', name: 'BANGLADESH (BGD)', prefix: '+880' },
  { code: 'BRB', name: 'BARBADOS (BRB)', prefix: '+1-246' },
  { code: 'BLR', name: 'BELARUS (BLR)', prefix: '+375' },
  { code: 'BEL', name: 'BELGIUM (BEL)', prefix: '+32' },
  { code: 'BLZ', name: 'BELIZE (BLZ)', prefix: '+501' },
  { code: 'BEN', name: 'BENIN (BEN)', prefix: '+229' },
  { code: 'BMU', name: 'BERMUDA (BMU)', prefix: '+1-441' },
  { code: 'BTN', name: 'BHUTAN (BTN)', prefix: '+975' },
  { code: 'BOL', name: 'BOLIVIA (BOL)', prefix: '+591' },
  { code: 'BIH', name: 'BOSNIA AND HERZEGOVINA (BIH)', prefix: '+387' },
  { code: 'BWA', name: 'BOTSWANA (BWA)', prefix: '+267' },
  { code: 'BVT', name: 'BOUVET ISLAND (BVT)', prefix: '+47' },
  { code: 'BRA', name: 'BRAZIL (BRA)', prefix: '+55' },
  { code: 'IOT', name: 'BRITISH INDIAN OCEAN TERRITORY (IOT)', prefix: '+246' },
  { code: 'BRN', name: 'BRUNEI DARUSSALAM (BRN)', prefix: '+673' },
  { code: 'BGR', name: 'BULGARIA (BGR)', prefix: '+359' },
  { code: 'BFA', name: 'BURKINA FASO (BFA)', prefix: '+226' },
  { code: 'BDI', name: 'BURUNDI (BDI)', prefix: '+257' },
  { code: 'KHM', name: 'CAMBODIA (KHM)', prefix: '+855' },
  { code: 'CMR', name: 'CAMEROON (CMR)', prefix: '+237' },
  { code: 'CAN', name: 'CANADA (CAN)', prefix: '+1' },
  { code: 'CPV', name: 'CAPE VERDE (CPV)', prefix: '+238' },
  { code: 'CYM', name: 'CAYMAN ISLANDS (CYM)', prefix: '+1-345' },
  { code: 'CAF', name: 'CENTRAL AFRICAN REPUBLIC (CAF)', prefix: '+236' },
  { code: 'TCD', name: 'CHAD (TCD)', prefix: '+235' },
  { code: 'CHL', name: 'CHILE (CHL)', prefix: '+56' },
  { code: 'CHN', name: 'CHINA (CHN)', prefix: '+86' },
  { code: 'CXR', name: 'CHRISTMAS ISLAND (CXR)', prefix: '+61' },
  { code: 'CCK', name: 'COCOS (KEELING) ISLANDS (CCK)', prefix: '+61' },
  { code: 'COL', name: 'COLOMBIA (COL)', prefix: '+57' },
  { code: 'COM', name: 'COMOROS (COM)', prefix: '+269' },
  { code: 'COG', name: 'CONGO (COG)', prefix: '+242' },
  { code: 'COD', name: 'CONGO, DEMOCRATIC REPUBLIC OF THE (COD)', prefix: '+243' },
  { code: 'COK', name: 'COOK ISLANDS (COK)', prefix: '+682' },
  { code: 'CRI', name: 'COSTA RICA (CRI)', prefix: '+506' },
  { code: 'CZE', name: 'CZECHIA (CZE)', prefix: '+420' },
  { code: 'CYP', name: 'CYPRUS (CYP)', prefix: '+357' },
  { code: 'DNK', name: 'DENMARK (DNK)', prefix: '+45' },
  { code: 'DJI', name: 'DJIBOUTI (DJI)', prefix: '+253' },
  { code: 'DMA', name: 'DOMINICA (DMA)', prefix: '+1-767' },
  { code: 'DOM', name: 'DOMINICAN REPUBLIC (DOM)', prefix: '+1-809, +1-829, +1-849' },
  { code: 'ECU', name: 'ECUADOR (ECU)', prefix: '+593' },
  { code: 'EGY', name: 'EGYPT (EGY)', prefix: '+20' },
  { code: 'SLV', name: 'EL SALVADOR (SLV)', prefix: '+503' },
  { code: 'GNQ', name: 'EQUATORIAL GUINEA (GNQ)', prefix: '+240' },
  { code: 'ERI', name: 'ERITREA (ERI)', prefix: '+291' },
  { code: 'EST', name: 'ESTONIA (EST)', prefix: '+372' },
  { code: 'ETH', name: 'ETHIOPIA (ETH)', prefix: '+251' },
  { code: 'FLK', name: 'FALKLAND ISLANDS (FLK)', prefix: '+500' },
  { code: 'FRO', name: 'FAROE ISLANDS (FRO)', prefix: '+298' },
  { code: 'FJI', name: 'FIJI (FJI)', prefix: '+679' },
  { code: 'FIN', name: 'FINLAND (FIN)', prefix: '+358' },
  { code: 'FRA', name: 'FRANCE (FRA)', prefix: '+33' },
  { code: 'GAB', name: 'GABON (GAB)', prefix: '+241' },
  { code: 'GMB', name: 'GAMBIA (GMB)', prefix: '+220' },
  { code: 'GEO', name: 'GEORGIA (GEO)', prefix: '+995' },
  { code: 'DEU', name: 'GERMANY (DEU)', prefix: '+49' },
  { code: 'GHA', name: 'GHANA (GHA)', prefix: '+233' },
  { code: 'GIB', name: 'GIBRALTAR (GIB)', prefix: '+350' },
  { code: 'GRC', name: 'GREECE (GRC)', prefix: '+30' },
  { code: 'GRL', name: 'GREENLAND (GRL)', prefix: '+299' },
  { code: 'GRD', name: 'GRENADA (GRD)', prefix: '+1-473' },
  { code: 'GLP', name: 'GUADELOUPE (GLP)', prefix: '+590' },
  { code: 'GUM', name: 'GUAM (GUM)', prefix: '+1-671' },
  { code: 'GTM', name: 'GUATEMALA (GTM)', prefix: '+502' },
  { code: 'GGY', name: 'GUERNSEY (GGY)', prefix: '+44-1481' },
  { code: 'GIN', name: 'GUINEA (GIN)', prefix: '+224' },
  { code: 'GNB', name: 'GUINEA-BISSAU (GNB)', prefix: '+245' },
  { code: 'GUY', name: 'GUYANA (GUY)', prefix: '+592' },
  { code: 'HTI', name: 'HAITI (HTI)', prefix: '+509' },
  { code: 'HMD', name: 'HEARD ISLAND AND MCDONALD ISLANDS (HMD)', prefix: '+672' },
  { code: 'VAT', name: 'HOLY SEE (VAT)', prefix: '+379' },
  { code: 'HND', name: 'HONDURAS (HND)', prefix: '+504' },
  { code: 'HUN', name: 'HUNGARY (HUN)', prefix: '+36' },
  { code: 'ISL', name: 'ICELAND (ISL)', prefix: '+354' },
  { code: 'IND', name: 'INDIA (IND)', prefix: '+91' },
  { code: 'IDN', name: 'INDONESIA (IDN)', prefix: '+62' },
  { code: 'IRN', name: 'IRAN, ISLAMIC REPUBLIC OF (IRN)', prefix: '+98' },
  { code: 'IRQ', name: 'IRAQ (IRQ)', prefix: '+964' },
  { code: 'IRL', name: 'IRELAND (IRL)', prefix: '+353' },
  { code: 'IMN', name: 'ISLE OF MAN (IMN)', prefix: '+44-1624' },
  { code: 'ISR', name: 'ISRAEL (ISR)', prefix: '+972' },
  { code: 'ITA', name: 'ITALY (ITA)', prefix: '+39' },
  { code: 'JAM', name: 'JAMAICA (JAM)', prefix: '+1-876' },
  { code: 'JPN', name: 'JAPAN (JPN)', prefix: '+81' },
  { code: 'JEY', name: 'JERSEY (JEY)', prefix: '+44-1534' },
  { code: 'JOR', name: 'JORDAN (JOR)', prefix: '+962' },
  { code: 'KAZ', name: 'KAZAKHSTAN (KAZ)', prefix: '+7' },
  { code: 'KEN', name: 'KENYA (KEN)', prefix: '+254' },
  { code: 'KIR', name: 'KIRIBATI (KIR)', prefix: '+686' },
  { code: 'PRK', name: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF (PRK)', prefix: '+850' },
  { code: 'KOR', name: 'KOREA, REPUBLIC OF (KOR)', prefix: '+82' },
  { code: 'KWT', name: 'KUWAIT (KWT)', prefix: '+965' },
  { code: 'KGZ', name: 'KYRGYZSTAN (KGZ)', prefix: '+996' },
  { code: 'LAO', name: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC (LAO)', prefix: '+856' },
  { code: 'LVA', name: 'LATVIA (LVA)', prefix: '+371' },
  { code: 'LBN', name: 'LEBANON (LBN)', prefix: '+961' },
  { code: 'LSO', name: 'LESOTHO (LSO)', prefix: '+266' },
  { code: 'LBR', name: 'LIBERIA (LBR)', prefix: '+231' },
  { code: 'LBY', name: 'LIBYA (LBY)', prefix: '+218' },
  { code: 'LIE', name: 'LIECHTENSTEIN (LIE)', prefix: '+423' },
  { code: 'LTU', name: 'LITHUANIA (LTU)', prefix: '+370' },
  { code: 'LUX', name: 'LUXEMBOURG (LUX)', prefix: '+352' },
  { code: 'MAC', name: 'MACAO (MAC)', prefix: '+853' },
  { code: 'MKD', name: 'NORTH MACEDONIA (MKD)', prefix: '+389' },
  { code: 'MDG', name: 'MADAGASCAR (MDG)', prefix: '+261' },
  { code: 'MWI', name: 'MALAWI (MWI)', prefix: '+265' },
  { code: 'MYS', name: 'MALAYSIA (MYS)', prefix: '+60' },
  { code: 'MDV', name: 'MALDIVES (MDV)', prefix: '+960' },
  { code: 'MLI', name: 'MALI (MLI)', prefix: '+223' },
  { code: 'MLT', name: 'MALTA (MLT)', prefix: '+356' },
  { code: 'MHL', name: 'MARSHALL ISLANDS (MHL)', prefix: '+692' },
  { code: 'MTQ', name: 'MARTINIQUE (MTQ)', prefix: '+596' },
  { code: 'MRT', name: 'MAURITANIA (MRT)', prefix: '+222' },
  { code: 'MUS', name: 'MAURITIUS (MUS)', prefix: '+230' },
  { code: 'MYT', name: 'MAYOTTE (MYT)', prefix: '+262' },
  { code: 'MEX', name: 'MEXICO (MEX)', prefix: '+52' },
  { code: 'FSM', name: 'MICRONESIA, FEDERATED STATES OF (FSM)', prefix: '+691' },
  { code: 'MDA', name: 'MOLDOVA, REPUBLIC OF (MDA)', prefix: '+373' },
  { code: 'MCO', name: 'MONACO (MCO)', prefix: '+377' },
  { code: 'MNG', name: 'MONGOLIA (MNG)', prefix: '+976' },
  { code: 'MNE', name: 'MONTENEGRO (MNE)', prefix: '+382' },
  { code: 'MSR', name: 'MONTSERRAT (MSR)', prefix: '+1-664' },
  { code: 'MAR', name: 'MOROCCO (MAR)', prefix: '+212' },
  { code: 'MOZ', name: 'MOZAMBIQUE (MOZ)', prefix: '+258' },
  { code: 'MMR', name: 'MYANMAR (MMR)', prefix: '+95' },
  { code: 'NAM', name: 'NAMIBIA (NAM)', prefix: '+264' },
  { code: 'NRU', name: 'NAURU (NRU)', prefix: '+674' },
  { code: 'NPL', name: 'NEPAL (NPL)', prefix: '+977' },
  { code: 'NLD', name: 'NETHERLANDS (NLD)', prefix: '+31' },
  { code: 'ANT', name: 'NETHERLANDS ANTILLES (ANT)', prefix: '+599' },
  { code: 'NCL', name: 'NEW CALEDONIA (NCL)', prefix: '+687' },
  { code: 'NZL', name: 'NEW ZEALAND (NZL)', prefix: '+64' },
  { code: 'NIC', name: 'NICARAGUA (NIC)', prefix: '+505' },
  { code: 'NER', name: 'NIGER (NER)', prefix: '+227' },
  { code: 'NGA', name: 'NIGERIA (NGA)', prefix: '+234' },
  { code: 'NIU', name: 'NIUE (NIU)', prefix: '+683' },
  { code: 'NFK', name: 'NORFOLK ISLAND (NFK)', prefix: '+672' },
  { code: 'MNP', name: 'NORTHERN MARIANA ISLANDS (MNP)', prefix: '+1-670' },
  { code: 'NOR', name: 'NORWAY (NOR)', prefix: '+47' },
  { code: 'OMN', name: 'OMAN (OMN)', prefix: '+968' },
  { code: 'PAK', name: 'PAKISTAN (PAK)', prefix: '+92' },
  { code: 'PLW', name: 'PALAU (PLW)', prefix: '+680' },
  { code: 'PSE', name: 'PALESTINE, STATE OF (PSE)', prefix: '+970' },
  { code: 'PAN', name: 'PANAMA (PAN)', prefix: '+507' },
  { code: 'PNG', name: 'PAPUA NEW GUINEA (PNG)', prefix: '+675' },
  { code: 'PRY', name: 'PARAGUAY (PRY)', prefix: '+595' },
  { code: 'PER', name: 'PERU (PER)', prefix: '+51' },
  { code: 'PHL', name: 'PHILIPPINES (PHL)', prefix: '+63' },
  { code: 'PCN', name: 'PITCAIRN (PCN)', prefix: '+870' },
  { code: 'POL', name: 'POLAND (POL)', prefix: '+48' },
  { code: 'PRT', name: 'PORTUGAL (PRT)', prefix: '+351' },
  { code: 'PRI', name: 'PUERTO RICO (PRI)', prefix: '+1-787, +1-939' },
  { code: 'QAT', name: 'QATAR (QAT)', prefix: '+974' },
  { code: 'REU', name: 'RÉUNION (REU)', prefix: '+262' },
  { code: 'ROU', name: 'ROMANIA (ROU)', prefix: '+40' },
  { code: 'RUS', name: 'RUSSIAN FEDERATION (RUS)', prefix: '+7' },
  { code: 'RWA', name: 'RWANDA (RWA)', prefix: '+250' },
  { code: 'BLM', name: 'SAINT-BARTHÉLEMY (BLM)', prefix: '+590' },
  { code: 'SHN', name: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA (SHN)', prefix: '+290' },
  { code: 'KNA', name: 'SAINT KITTS AND NEVIS (KNA)', prefix: '+1-869' },
  { code: 'LCA', name: 'SAINT LUCIA (LCA)', prefix: '+1-758' },
  { code: 'MAF', name: 'SAINT MARTIN (FRENCH) (MAF)', prefix: '+590' },
  { code: 'SPM', name: 'SAINT PIERRE AND MIQUELON (SPM)', prefix: '+508' },
  { code: 'VCT', name: 'SAINT VINCENT AND THE GRENADINES (VCT)', prefix: '+1-784' },
  { code: 'WSM', name: 'SAMOA (WSM)', prefix: '+685' },
  { code: 'SMR', name: 'SAN MARINO (SMR)', prefix: '+378' },
  { code: 'STP', name: 'SAO TOME AND PRINCIPE (STP)', prefix: '+239' },
  { code: 'SAU', name: 'SAUDI ARABIA (SAU)', prefix: '+966' },
  { code: 'SEN', name: 'SENEGAL (SEN)', prefix: '+221' },
  { code: 'SRB', name: 'SERBIA (SRB)', prefix: '+381' },
  { code: 'SYC', name: 'SEYCHELLES (SYC)', prefix: '+248' },
  { code: 'SLE', name: 'SIERRA LEONE (SLE)', prefix: '+232' },
  { code: 'SGP', name: 'SINGAPORE (SGP)', prefix: '+65' },
  { code: 'SVK', name: 'SLOVAKIA (SVK)', prefix: '+421' },
  { code: 'SVN', name: 'SLOVENIA (SVN)', prefix: '+386' },
  { code: 'SLB', name: 'SOLOMON ISLANDS (SLB)', prefix: '+677' },
  { code: 'SOM', name: 'SOMALIA (SOM)', prefix: '+252' },
  { code: 'ZAF', name: 'SOUTH AFRICA (ZAF)', prefix: '+27' },
  { code: 'SGS', name: 'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS (SGS)', prefix: '+500' },
  { code: 'SSD', name: 'SOUTH SUDAN (SSD)', prefix: '+211' },
  { code: 'ESP', name: 'SPAIN (ESP)', prefix: '+34' },
  { code: 'LKA', name: 'SRI LANKA (LKA)', prefix: '+94' },
  { code: 'SDN', name: 'SUDAN (SDN)', prefix: '+249' },
  { code: 'SUR', name: 'SURINAME (SUR)', prefix: '+597' },
  { code: 'SJM', name: 'SVALBARD AND JAN MAYEN (SJM)', prefix: '+47' },
  { code: 'SWZ', name: 'ESWATINI (SWZ)', prefix: '+268' },
  { code: 'SWE', name: 'SWEDEN (SWE)', prefix: '+46' },
  { code: 'CHE', name: 'SWITZERLAND (CHE)', prefix: '+41' },
  { code: 'SYR', name: 'SYRIAN ARAB REPUBLIC (SYR)', prefix: '+963' },
  { code: 'TWN', name: 'TAIWAN (TWN)', prefix: '+886' },
  { code: 'TJK', name: 'TAJIKISTAN (TJK)', prefix: '+992' },
  { code: 'TZA', name: 'TANZANIA, UNITED REPUBLIC OF (TZA)', prefix: '+255' },
  { code: 'THA', name: 'THAILAND (THA)', prefix: '+66' },
  { code: 'TLS', name: 'TIMOR-LESTE (TLS)', prefix: '+670' },
  { code: 'TGO', name: 'TOGO (TGO)', prefix: '+228' },
  { code: 'TKL', name: 'TOKELAU (TKL)', prefix: '+690' },
  { code: 'TON', name: 'TONGA (TON)', prefix: '+676' },
  { code: 'TTO', name: 'TRINIDAD AND TOBAGO (TTO)', prefix: '+1-868' },
  { code: 'TUN', name: 'TUNISIA (TUN)', prefix: '+216' },
  { code: 'TUR', name: 'TURKIYE (TUR)', prefix: '+90' },
  { code: 'TKM', name: 'TURKMENISTAN (TKM)', prefix: '+993' },
  { code: 'TCA', name: 'TURKS AND CAICOS ISLANDS (TCA)', prefix: '+1-649' },
  { code: 'TUV', name: 'TUVALU (TUV)', prefix: '+688' },
  { code: 'UGA', name: 'UGANDA (UGA)', prefix: '+256' },
  { code: 'UKR', name: 'UKRAINE (UKR)', prefix: '+380' },
  { code: 'ARE', name: 'UNITED ARAB EMIRATES (ARE)', prefix: '+971' },
  { code: 'GBR', name: 'UNITED KINGDOM (GBR)', prefix: '+44' },
  { code: 'USA', name: 'UNITED STATES (USA)', prefix: '+1' },
  { code: 'UMI', name: 'UNITED STATES MINOR OUTLYING ISLANDS (UMI)', prefix: '+1' },
  { code: 'URY', name: 'URUGUAY (URY)', prefix: '+598' },
  { code: 'UZB', name: 'UZBEKISTAN (UZB)', prefix: '+998' },
  { code: 'VUT', name: 'VANUATU (VUT)', prefix: '+678' },
  { code: 'VEN', name: 'VENEZUELA (VEN)', prefix: '+58' },
  { code: 'VNM', name: 'VIET NAM (VNM)', prefix: '+84' },
  { code: 'VGB', name: 'VIRGIN ISLANDS (BRITISH) (VGB)', prefix: '+1-284' },
  { code: 'VIR', name: 'VIRGIN ISLANDS (U.S.) (VIR)', prefix: '+1-340' },
  { code: 'WLF', name: 'WALLIS AND FUTUNA (WLF)', prefix: '+681' },
  { code: 'ESH', name: 'WESTERN SAHARA (ESH)', prefix: '+212' },
  { code: 'YEM', name: 'YEMEN (YEM)', prefix: '+967' },
  { code: 'ZMB', name: 'ZAMBIA (ZMB)', prefix: '+260' },
  { code: 'ZWE', name: 'ZIMBABWE (ZWE)', prefix: '+263' }
];


export const phoneTypes = ['Mobile', 'Home', 'Work', 'Other']

export const days = Array.from({ length: 31 }, (_, i) =>
	(i + 1).toString().padStart(2, '0')
)
export const months = [
	{ value: '01', label: 'January' },
	{ value: '02', label: 'February' },
	{ value: '03', label: 'March' },
	{ value: '04', label: 'April' },
	{ value: '05', label: 'May' },
	{ value: '06', label: 'June' },
	{ value: '07', label: 'July' },
	{ value: '08', label: 'August' },
	{ value: '09', label: 'September' },
	{ value: '10', label: 'October' },
	{ value: '11', label: 'November' },
	{ value: '12', label: 'December' },
]
export const yearsDob = Array.from({ length: 120 }, (_, i) =>
	(new Date().getFullYear() - i).toString()
)
export const yearsPassportIssue = Array.from({ length: 20 }, (_, i) =>
	(new Date().getFullYear() - i).toString()
)
export const yearsPassportExpiry = Array.from({ length: 15 }, (_, i) =>
	(new Date().getFullYear() + i).toString()
)

export const mandatoryQuestions = {
	a: `Do you have a physical or mental disorder; or are you a drug abuser or addict; or do you currently have any of the following diseases (communicable diseases are specified pursuant to section 361(b) of the “Public Health Service Act)”:
Cholera
Diphtheria
Tuberculosis, infectious
Plague
Smallpox
Yellow Fever
Viral Hemorrhagic Fevers, including Ebola, Lassa, Marburg, Crimean-Congo
Severe acute respiratory illnesses capable of transmission to other persons and likely to cause mortality.`,
	b: 'Have you ever been arrested or convicted for a crime that resulted in serious damage to property, or serious harm to another person or government authority?',
	c: 'Have you ever violated any law related to possessing, using, or distributing illegal drugs?',
	d: 'Do you seek to engage in or have you ever engaged in terrorist activities, espionage, sabotage, or genocide?',
	e: 'Have you ever committed fraud or misrepresented yourself or others to obtain, or assist others to obtain, a visa or entry into the United States?',
	f: "Are you currently seeking employment in the United States or were you previously employed in the United States without prior permission from the U.S. government?",
	g: "Have you ever been denied a U.S. visa you applied for with your current or previous passport, or have you ever been refused admission to the United States or withdrawn your application for admission at a U.S. port of entry?",
	h: "Have you ever stayed in the United States longer than the admission period granted to you by the U.S. government?",
	i: "Have you traveled to, or been present in Iraq, North Korea, Syria, Iran, Sudan, Libya, Somalia or Yemen on or after March 1, 2011?",
	j: "Have you traveled to, or been present in Cuba on or after March 1, 2011?"
}
