
export type Form = {
	email: string;
	confirmEmail: string;
	altEmail?: string;
	phoneType: string;
	phonePrefix: string;
	phoneNumber: string;
	lastName: string;
	givenNames: string;
	aliases: 'Yes' | 'No';
	dobDay: string;
	dobMonth: string;
	dobYear: string;
	birthCity: string;
	birthCountry: string;
	parent1LastName: string;
	parent1FirstName: string;
	parent2LastName: string;
	parent2FirstName: string;
	passportCountry: string;
	passportIssuedDay: string;
	passportIssuedMonth: string;
	passportIssuedYear: string;
	passportExpiryDay: string;
	passportExpiryMonth: string;
	passportExpiryYear: string;
	passportNumber: string;
	citizenshipCountry: string;
	gender: 'Male' | 'Female' | 'Other';
	passportFile: FileList;
	otherCitizenship: 'Yes' | 'No';
	otherPassportIssued: 'Yes' | 'No';
	homeCountry: string;
	streetAddress: string;
	addressLine2?: string;
	city: string;
	zipCode: string;
	billingSame: 'Yes' | 'No';
	socialMediaDisclose: 'Yes' | 'No';
	currentEmployer: 'Yes' | 'No';
	travelItinerary: 'transit' | 'stay';
	questionA: 'Yes' | 'No';
	questionB: 'Yes' | 'No';
	questionC: 'Yes' | 'No';
	questionD: 'Yes' | 'No';
	questionE: 'Yes' | 'No';
	questionF: 'Yes' | 'No';
	questionG: 'Yes' | 'No';
	questionH: 'Yes' | 'No';
	questionI: 'Yes' | 'No';
	questionJ: 'Yes' | 'No';
	emergencyLastName: string;
	emergencyFirstName: string;
	emergencyPhonePrefix: string;
	emergencyPhoneNumber: string;
	emergencyEmail: string;
};