export const TRANSLATIONS = {
	en: {
		statsTitle: 'Fast and Secure visa application support.',
		stats: [
			{ value: '98%', label: 'Approval Rate' },
			{ value: '100k+', label: 'Processed Applications' },
			{ value: '24/7', label: 'Customer Support' },
		],
		trustTitle: 'Why Travelers Trust Our Visa Support Services',
		trustDescription:
			'We help you apply online with expert assistance, secure processing, and a 100% money-back guarantee.',
		trustItems: [
			{
				title: 'We’re on Trustpilot',
				desc: 'Trusted by customers worldwide, as seen on Trustpilot.',
			},
			{
				title: 'Encrypted Data. Certified Business.',
				desc: 'Daily security checks help protect your data and keep our platform safe.',
			},
			{
				title: 'Your personal data is protected.',
				desc: 'We are committed to GDPR compliance and safeguarding your data privacy.',
			},
		],
		serviceTitle: 'Our ESTA Application Service',
		serviceDescription:
			'Travelers use our visa processing service because we make the process simpler, faster, and less stressful, especially if you’re unsure about eligibility, need help with forms, or want peace of mind knowing your application is thoroughly reviewed and error-free. Your data is always encrypted and secure. Our service is optional and designed for convenience.',
		howHelpTitle: 'Here’s how we help:',
		howHelpList: [
			'Expert support to avoid common mistakes that can lead to rejections or delays',
			'Same-day processing in most cases',
			'100% money-back guarantee if your application is not approved',
			'Application review by trained visa advisors',
			'Multilingual 24/7 customer support',
			'Data is encrypted and handled securely.',
		],
		startApplication: 'START APPLICATION',
		visaCountriesTitle: 'The 42 Visa Waiver Program Member Countries:',
		visaCountries: [
			'Andorra',
			'Australia',
			'Austria',
			'Belgium',
			'Brunei',
			'Chile',
			'Croatia',
			'Czech Republic',
			'Denmark',
			'Estonia',
			'Finland',
			'France',
			'Germany',
			'Greece',
			'Hungary',
			'Iceland',
			'Ireland',
			'Israel',
			'Italy',
			'Japan',
			'South Korea',
			'Latvia',
			'Liechtenstein',
			'Lithuania',
			'Luxembourg',
			'Malta',
			'Monaco',
			'Netherlands',
			'New Zealand',
			'Norway',
			'Poland',
			'Portugal',
			'Qatar',
			'San Marino',
			'Singapore',
			'Slovakia',
			'Slovenia',
			'Spain',
			'Sweden',
			'Switzerland',
			'Taiwan',
			'United Kingdom',
		],
		infoTitle: 'Information:',
		infoText:
			'This website is not affiliated with any government agency. We are a private company dedicated to assisting international travelers in applying for Electronic Visas and Travel Authorizations. While we are not connected to any government authority, we simplify the official application process through expert support and secure online tools.\n\nOur platform offers step-by-step guidance to help ensure that each application is complete and accurate. Applicants may also choose to apply directly through the official government website without using our services. We charge a total fee of $139 per application, which includes both the official ESTA government fee and our service fee. Our services include 24/7 customer support, a 90-day money-back guarantee, and a no-charge policy for unapproved applications. We look forward to assisting you and helping ensure you have a safe and pleasant journey.',
		accreditationTitle: 'Accreditations:',
		accreditationText:
			'We hold multiple accreditations in the immigration and travel industries, reflecting our commitment to professionalism, regulatory compliance, and exceptional customer service. Our accreditations demonstrate our core values of transparency, integrity, and dedication to delivering high-quality support throughout the travel authorization process.\n\nWe are officially registered with the New Zealand Immigration Advisers Authority (IAA) under registration number 201500355, and with the Australian Migration Agents Registration Authority (MARA) under registration number 1466320. These registrations affirm that we meet the strict professional and ethical standards required to provide immigration-related guidance in both jurisdictions. In addition, ETAS Travel LLC is a member of the American Society of Travel Advisors (ASTA), registration number 900387792, further emphasizing our commitment to ethical travel practices and industry excellence.',
	},

	es: {
		statsTitle: 'Soporte rápido y seguro para la solicitud de visa.',
		stats: [
			{ value: '98%', label: 'Tasa de Aprobación' },
			{ value: '100k+', label: 'Solicitudes Procesadas' },
			{ value: '24/7', label: 'Atención al Cliente' },
		],
		trustTitle:
			'Por qué los viajeros confían en nuestros servicios de apoyo para visas',
		trustDescription:
			'Le ayudamos a solicitar en línea con asistencia experta, procesamiento seguro y garantía de devolución del 100% del dinero.',
		trustItems: [
			{
				title: 'Estamos en Trustpilot',
				desc: 'Confiado por clientes de todo el mundo, como se ve en Trustpilot.',
			},
			{
				title: 'Datos encriptados. Negocio certificado.',
				desc: 'Controles de seguridad diarios para proteger sus datos y mantener nuestra plataforma segura.',
			},
			{
				title: 'Sus datos personales están protegidos.',
				desc: 'Estamos comprometidos con el cumplimiento del GDPR y la protección de su privacidad.',
			},
		],
		serviceTitle: 'Nuestro Servicio de Solicitud ESTA',
		serviceDescription:
			'Los viajeros usan nuestro servicio de procesamiento de visas porque hacemos el proceso más simple, rápido y menos estresante, especialmente si no está seguro sobre la elegibilidad, necesita ayuda con los formularios o quiere la tranquilidad de saber que su solicitud es revisada a fondo y sin errores. Sus datos siempre están encriptados y seguros. Nuestro servicio es opcional y está diseñado para su conveniencia.',
		howHelpTitle: 'Así es como ayudamos:',
		howHelpList: [
			'Soporte experto para evitar errores comunes que pueden causar rechazos o retrasos',
			'Procesamiento el mismo día en la mayoría de los casos',
			'Garantía de devolución del 100% del dinero si su solicitud no es aprobada',
			'Revisión de solicitudes por asesores de visas capacitados',
			'Atención al cliente multilingüe 24/7',
			'Los datos se encriptan y manejan de manera segura.',
		],
		startApplication: 'COMENZAR LA SOLICITUD',
		visaCountriesTitle:
			'Los 42 países miembros del Programa de Exención de Visa:',
		visaCountries: [
			'Andorra',
			'Australia',
			'Austria',
			'Bélgica',
			'Brunéi',
			'Chile',
			'Croacia',
			'República Checa',
			'Dinamarca',
			'Estonia',
			'Finlandia',
			'Francia',
			'Alemania',
			'Grecia',
			'Hungría',
			'Islandia',
			'Irlanda',
			'Israel',
			'Italia',
			'Japón',
			'Corea del Sur',
			'Letonia',
			'Liechtenstein',
			'Lituania',
			'Luxemburgo',
			'Malta',
			'Mónaco',
			'Países Bajos',
			'Nueva Zelanda',
			'Noruega',
			'Polonia',
			'Portugal',
			'Catar',
			'San Marino',
			'Singapur',
			'Eslovaquia',
			'Eslovenia',
			'España',
			'Suecia',
			'Suiza',
			'Taiwán',
			'Reino Unido',
		],
		infoTitle: 'Información:',
		infoText:
			'Este sitio web no está afiliado a ninguna agencia gubernamental. Somos una empresa privada dedicada a ayudar a viajeros internacionales a solicitar visas electrónicas y autorizaciones de viaje. Aunque no estamos conectados a ninguna autoridad gubernamental, simplificamos el proceso oficial a través de asistencia experta y herramientas en línea seguras.\n\nNuestra plataforma ofrece una guía paso a paso para asegurar que cada solicitud esté completa y sea precisa. Los solicitantes también pueden optar por aplicar directamente a través del sitio web oficial del gobierno sin usar nuestros servicios. Cobramos una tarifa total de $139 por solicitud, que incluye tanto la tarifa oficial del gobierno ESTA como nuestra tarifa de servicio. Nuestros servicios incluyen atención al cliente 24/7, garantía de devolución de dinero de 90 días y política de no cobro para solicitudes no aprobadas. Esperamos poder asistirle y ayudar a garantizar que tenga un viaje seguro y agradable.',
		accreditationTitle: 'Acreditaciones:',
		accreditationText:
			'Poseemos múltiples acreditaciones en las industrias de inmigración y viajes, que reflejan nuestro compromiso con el profesionalismo, el cumplimiento normativo y un servicio al cliente excepcional. Nuestras acreditaciones demuestran nuestros valores fundamentales de transparencia, integridad y dedicación a brindar un soporte de alta calidad durante todo el proceso de autorización de viaje.\n\nEstamos oficialmente registrados en la Autoridad de Asesores de Inmigración de Nueva Zelanda (IAA) bajo el número de registro 201500355, y en la Autoridad de Registro de Agentes de Migración de Australia (MARA) bajo el número 1466320. Estas inscripciones afirman que cumplimos con los estrictos estándares profesionales y éticos requeridos para proporcionar orientación relacionada con inmigración en ambas jurisdicciones. Además, ETAS Travel LLC es miembro de la Sociedad Americana de Asesores de Viajes (ASTA), número de registro 900387792, lo que enfatiza nuestro compromiso con las prácticas éticas de viaje y la excelencia en la industria.',
	},

	de: {
		statsTitle:
			'Schnelle und sichere Unterstützung bei der Visumantragstellung.',
		stats: [
			{ value: '98%', label: 'Genehmigungsrate' },
			{ value: '100k+', label: 'Verarbeitete Anträge' },
			{ value: '24/7', label: 'Kundensupport' },
		],
		trustTitle: 'Warum Reisende unseren Visa-Support-Diensten vertrauen',
		trustDescription:
			'Wir helfen Ihnen, online mit fachkundiger Unterstützung, sicherer Verarbeitung und 100 % Geld-zurück-Garantie zu beantragen.',
		trustItems: [
			{
				title: 'Wir sind bei Trustpilot',
				desc: 'Von Kunden weltweit vertrauenswürdig, wie bei Trustpilot zu sehen.',
			},
			{
				title: 'Verschlüsselte Daten. Zertifiziertes Unternehmen.',
				desc: 'Tägliche Sicherheitsprüfungen schützen Ihre Daten und halten unsere Plattform sicher.',
			},
			{
				title: 'Ihre persönlichen Daten sind geschützt.',
				desc: 'Wir verpflichten uns zur Einhaltung der DSGVO und zum Schutz Ihrer Privatsphäre.',
			},
		],
		serviceTitle: 'Unser ESTA-Antragsservice',
		serviceDescription:
			'Reisende nutzen unseren Visa-Verarbeitungsservice, weil wir den Prozess einfacher, schneller und stressfreier machen, besonders wenn Sie sich bezüglich der Berechtigung unsicher sind, Hilfe bei Formularen benötigen oder beruhigt sein möchten, dass Ihr Antrag sorgfältig geprüft und fehlerfrei ist. Ihre Daten sind stets verschlüsselt und sicher. Unser Service ist optional und auf Bequemlichkeit ausgelegt.',
		howHelpTitle: 'So helfen wir:',
		howHelpList: [
			'Fachkundige Unterstützung zur Vermeidung häufiger Fehler, die zu Ablehnungen oder Verzögerungen führen können',
			'Bearbeitung am selben Tag in den meisten Fällen',
			'100 % Geld-zurück-Garantie, wenn Ihr Antrag nicht genehmigt wird',
			'Antragsprüfung durch geschulte Visa-Berater',
			'Mehrsprachiger 24/7-Kundensupport',
			'Daten werden verschlüsselt und sicher verarbeitet.',
		],
		startApplication: 'ANTRAG STARTEN',
		visaCountriesTitle: 'Die 42 Mitgliedsländer des Visa-Waiver-Programms:',
		visaCountries: [
			'Andorra',
			'Australien',
			'Österreich',
			'Belgien',
			'Brunei',
			'Chile',
			'Kroatien',
			'Tschechien',
			'Dänemark',
			'Estland',
			'Finnland',
			'Frankreich',
			'Deutschland',
			'Griechenland',
			'Ungarn',
			'Island',
			'Irland',
			'Israel',
			'Italien',
			'Japan',
			'Südkorea',
			'Lettland',
			'Liechtenstein',
			'Litauen',
			'Luxemburg',
			'Malta',
			'Monaco',
			'Niederlande',
			'Neuseeland',
			'Norwegen',
			'Polen',
			'Portugal',
			'Katar',
			'San Marino',
			'Singapur',
			'Slowakei',
			'Slowenien',
			'Spanien',
			'Schweden',
			'Schweiz',
			'Taiwan',
			'Vereinigtes Königreich',
		],
		infoTitle: 'Informationen:',
		infoText:
			'Diese Website ist nicht mit einer Regierungsbehörde verbunden. Wir sind ein privates Unternehmen, das internationale Reisende bei der Beantragung von elektronischen Visa und Reisegenehmigungen unterstützt. Obwohl wir nicht mit einer Regierungsbehörde verbunden sind, vereinfachen wir den offiziellen Antragsprozess durch fachkundige Unterstützung und sichere Online-Tools.\n\nUnsere Plattform bietet eine schrittweise Anleitung, um sicherzustellen, dass jeder Antrag vollständig und korrekt ist. Antragsteller können auch direkt über die offizielle Regierungswebsite ohne Nutzung unserer Dienste beantragen. Wir berechnen eine Gesamtgebühr von 139 $ pro Antrag, die sowohl die offizielle ESTA-Regierungsgebühr als auch unsere Servicegebühr umfasst. Unsere Dienstleistungen beinhalten 24/7 Kundensupport, eine 90-Tage-Geld-zurück-Garantie und eine kostenfreie Politik für nicht genehmigte Anträge. Wir freuen uns, Ihnen zu helfen und eine sichere und angenehme Reise zu gewährleisten.',
		accreditationTitle: 'Akkreditierungen:',
		accreditationText:
			'Wir verfügen über mehrere Akkreditierungen in den Bereichen Einwanderung und Reisen, die unser Engagement für Professionalität, gesetzliche Compliance und hervorragenden Kundenservice widerspiegeln. Unsere Akkreditierungen zeigen unsere Grundwerte Transparenz, Integrität und Engagement für die Bereitstellung hochwertiger Unterstützung während des gesamten Reisegenehmigungsprozesses.\n\nWir sind offiziell bei der Neuseeländischen Behörde für Einwanderungsberater (IAA) unter der Registrierungsnummer 201500355 und bei der Australischen Behörde für Migration Agenten Registrierung (MARA) unter der Registrierungsnummer 1466320 registriert. Diese Registrierungen bestätigen, dass wir die strengen professionellen und ethischen Standards erfüllen, die für die Bereitstellung von migrationsbezogener Beratung in beiden Gerichtsbarkeiten erforderlich sind. Zusätzlich ist ETAS Travel LLC Mitglied der American Society of Travel Advisors (ASTA), Registrierungsnummer 900387792, was unser Engagement für ethische Reisepraktiken und Branchenexzellenz unterstreicht.',
	},

	fr: {
		statsTitle: 'Support rapide et sécurisé pour la demande de visa.',
		stats: [
			{ value: '98%', label: "Taux d'approbation" },
			{ value: '100k+', label: 'Demandes traitées' },
			{ value: '24/7', label: 'Service client' },
		],
		trustTitle:
			"Pourquoi les voyageurs font confiance à nos services d'assistance aux visas",
		trustDescription:
			'Nous vous aidons à postuler en ligne avec une assistance experte, un traitement sécurisé et une garantie de remboursement à 100%.',
		trustItems: [
			{
				title: 'Nous sommes sur Trustpilot',
				desc: 'Approuvé par des clients du monde entier, comme on le voit sur Trustpilot.',
			},
			{
				title: 'Données cryptées. Entreprise certifiée.',
				desc: 'Des contrôles de sécurité quotidiens protègent vos données et maintiennent notre plateforme sûre.',
			},
			{
				title: 'Vos données personnelles sont protégées.',
				desc: 'Nous nous engageons à respecter le RGPD et à protéger votre vie privée.',
			},
		],
		serviceTitle: 'Notre service de demande ESTA',
		serviceDescription:
			"Les voyageurs utilisent notre service de traitement des visas parce que nous rendons le processus plus simple, plus rapide et moins stressant, surtout si vous n'êtes pas sûr de votre admissibilité, avez besoin d'aide avec les formulaires ou souhaitez l'assurance que votre demande est minutieusement examinée et sans erreur. Vos données sont toujours cryptées et sécurisées. Notre service est optionnel et conçu pour votre commodité.",
		howHelpTitle: 'Voici comment nous aidons :',
		howHelpList: [
			'Assistance experte pour éviter les erreurs courantes pouvant entraîner des rejets ou des retards',
			'Traitement le jour même dans la plupart des cas',
			"Garantie de remboursement à 100 % si votre demande n'est pas approuvée",
			'Examen des demandes par des conseillers en visas qualifiés',
			'Support client multilingue 24/7',
			'Les données sont cryptées et traitées en toute sécurité.',
		],
		startApplication: 'COMMENCER LA DEMANDE',
		visaCountriesTitle:
			"Les 42 pays membres du programme d'exemption de visa :",
		visaCountries: [
			'Andorre',
			'Australie',
			'Autriche',
			'Belgique',
			'Brunei',
			'Chili',
			'Croatie',
			'République tchèque',
			'Danemark',
			'Estonie',
			'Finlande',
			'France',
			'Allemagne',
			'Grèce',
			'Hongrie',
			'Islande',
			'Irlande',
			'Israël',
			'Italie',
			'Japon',
			'Corée du Sud',
			'Lettonie',
			'Liechtenstein',
			'Lituanie',
			'Luxembourg',
			'Malte',
			'Monaco',
			'Pays-Bas',
			'Nouvelle-Zélande',
			'Norvège',
			'Pologne',
			'Portugal',
			'Qatar',
			'Saint-Marin',
			'Singapour',
			'Slovaquie',
			'Slovénie',
			'Espagne',
			'Suède',
			'Suisse',
			'Taïwan',
			'Royaume-Uni',
		],
		infoTitle: 'Informations :',
		infoText:
			"Ce site web n'est affilié à aucune agence gouvernementale. Nous sommes une entreprise privée dédiée à l'assistance des voyageurs internationaux pour la demande de visas électroniques et d'autorisations de voyage. Bien que nous ne soyons pas liés à une autorité gouvernementale, nous simplifions le processus officiel grâce à un soutien expert et des outils en ligne sécurisés.\n\nNotre plateforme offre un accompagnement étape par étape pour garantir que chaque demande soit complète et précise. Les candidats peuvent également choisir de postuler directement via le site officiel du gouvernement sans utiliser nos services. Nous facturons des frais totaux de 139 $ par demande, incluant les frais officiels ESTA du gouvernement et nos frais de service. Nos services incluent un support client 24/7, une garantie de remboursement sous 90 jours et une politique de non-facturation pour les demandes non approuvées. Nous sommes impatients de vous aider et de vous assurer un voyage sûr et agréable.",
		accreditationTitle: 'Accréditations :',
		accreditationText:
			"Nous détenons plusieurs accréditations dans les secteurs de l'immigration et du voyage, reflétant notre engagement envers le professionnalisme, la conformité réglementaire et un service client exceptionnel. Nos accréditations démontrent nos valeurs fondamentales de transparence, d'intégrité et de dévouement à fournir un soutien de haute qualité tout au long du processus d'autorisation de voyage.\n\nNous sommes officiellement enregistrés auprès de l'Autorité des conseillers en immigration de Nouvelle-Zélande (IAA) sous le numéro d'enregistrement 201500355, et auprès de l'Autorité australienne d'enregistrement des agents de migration (MARA) sous le numéro 1466320. Ces enregistrements affirment que nous respectons les normes professionnelles et éthiques strictes requises pour fournir des conseils en matière d'immigration dans les deux juridictions. De plus, ETAS Travel LLC est membre de l'American Society of Travel Advisors (ASTA), numéro d'enregistrement 900387792, soulignant notre engagement envers des pratiques de voyage éthiques et l'excellence du secteur.",
	},

	it: {
		statsTitle: 'Supporto rapido e sicuro per la domanda di visto.',
		stats: [
			{ value: '98%', label: 'Tasso di approvazione' },
			{ value: '100k+', label: 'Domande elaborate' },
			{ value: '24/7', label: 'Assistenza clienti' },
		],
		trustTitle:
			'Perché i viaggiatori si affidano ai nostri servizi di supporto per i visti',
		trustDescription:
			'Ti aiutiamo a fare domanda online con assistenza esperta, elaborazione sicura e garanzia di rimborso al 100%.',
		trustItems: [
			{
				title: 'Siamo su Trustpilot',
				desc: 'Approvato da clienti in tutto il mondo, come si vede su Trustpilot.',
			},
			{
				title: 'Dati criptati. Azienda certificata.',
				desc: 'Controlli di sicurezza giornalieri aiutano a proteggere i tuoi dati e mantenere la nostra piattaforma sicura.',
			},
			{
				title: 'I tuoi dati personali sono protetti.',
				desc: 'Siamo impegnati nella conformità al GDPR e nella tutela della tua privacy.',
			},
		],
		serviceTitle: 'Il nostro servizio di richiesta ESTA',
		serviceDescription:
			'I viaggiatori usano il nostro servizio di elaborazione visti perché rendiamo il processo più semplice, veloce e meno stressante, soprattutto se non sei sicuro dell’idoneità, hai bisogno di aiuto con i moduli o vuoi la tranquillità di sapere che la tua domanda è accuratamente revisionata e senza errori. I tuoi dati sono sempre criptati e sicuri. Il nostro servizio è opzionale e progettato per comodità.',
		howHelpTitle: 'Ecco come ti aiutiamo:',
		howHelpList: [
			'Supporto esperto per evitare errori comuni che possono causare rifiuti o ritardi',
			'Elaborazione nello stesso giorno nella maggior parte dei casi',
			'Garanzia di rimborso al 100% se la tua domanda non viene approvata',
			'Revisione delle domande da parte di consulenti per visti qualificati',
			'Supporto clienti multilingue 24/7',
			'I dati sono criptati e gestiti in modo sicuro.',
		],
		startApplication: 'INIZIA LA DOMANDA',
		visaCountriesTitle: 'I 42 paesi membri del programma Visa Waiver:',
		visaCountries: [
			'Andorra',
			'Australia',
			'Austria',
			'Belgio',
			'Brunei',
			'Cile',
			'Croazia',
			'Repubblica Ceca',
			'Danimarca',
			'Estonia',
			'Finlandia',
			'Francia',
			'Germania',
			'Grecia',
			'Ungheria',
			'Islanda',
			'Irlanda',
			'Israele',
			'Italia',
			'Giappone',
			'Corea del Sud',
			'Lettonia',
			'Liechtenstein',
			'Lituania',
			'Lussemburgo',
			'Malta',
			'Monaco',
			'Paesi Bassi',
			'Nuova Zelanda',
			'Norvegia',
			'Polonia',
			'Portogallo',
			'Qatar',
			'San Marino',
			'Singapore',
			'Slovacchia',
			'Slovenia',
			'Spagna',
			'Svezia',
			'Svizzera',
			'Taiwan',
			'Regno Unito',
		],
		infoTitle: 'Informazioni:',
		infoText:
			'Questo sito web non è affiliato a nessuna agenzia governativa. Siamo una società privata dedicata ad assistere i viaggiatori internazionali nella richiesta di visti elettronici e autorizzazioni di viaggio. Sebbene non siamo collegati ad alcuna autorità governativa, semplifichiamo il processo ufficiale tramite supporto esperto e strumenti online sicuri.\n\nLa nostra piattaforma offre una guida passo dopo passo per garantire che ogni domanda sia completa e accurata. I richiedenti possono anche scegliere di presentare la domanda direttamente tramite il sito ufficiale del governo senza utilizzare i nostri servizi. Applichiamo una tariffa totale di 139 $ per domanda, che include sia la tassa ufficiale ESTA del governo che la nostra tariffa di servizio. I nostri servizi includono assistenza clienti 24/7, garanzia di rimborso di 90 giorni e politica di nessun addebito per domande non approvate. Siamo lieti di assisterti e di aiutarti a garantire un viaggio sicuro e piacevole.',
		accreditationTitle: 'Accreditamenti:',
		accreditationText:
			'Deteniamo molteplici accreditamenti nei settori dell’immigrazione e dei viaggi, riflettendo il nostro impegno per la professionalità, la conformità normativa e un servizio clienti eccezionale. I nostri accreditamenti dimostrano i nostri valori fondamentali di trasparenza, integrità e dedizione a fornire supporto di alta qualità durante l’intero processo di autorizzazione al viaggio.\n\nSiamo ufficialmente registrati presso la New Zealand Immigration Advisers Authority (IAA) con il numero di registrazione 201500355 e presso l’Australian Migration Agents Registration Authority (MARA) con il numero 1466320. Queste registrazioni confermano che soddisfiamo i rigorosi standard professionali ed etici richiesti per fornire consulenza in materia di immigrazione in entrambe le giurisdizioni. Inoltre, ETAS Travel LLC è membro della American Society of Travel Advisors (ASTA), numero di registrazione 900387792, sottolineando il nostro impegno per pratiche di viaggio etiche e l’eccellenza del settore.',
	},
}

export const LANGS = [
	{ code: 'en', label: 'English' },
	{ code: 'es', label: 'Spanish' },
	{ code: 'de', label: 'German' },
	{ code: 'fr', label: 'French' },
	{ code: 'it', label: 'Italian' },
] as const